AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 bucket with specified permissions.
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: json-store-acm
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
                - mediaconvert.amazonaws.com
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${MyBucket}/*"
              - !Sub "arn:aws:s3:::${MyBucket}"
